name: Build & deploy to GitHub Pages

# Run on pushes to main (adjust branch if needed)
on:
    push:
        branches: [main]

permissions:
    contents: read # for actions/checkout
    pages: write # to deploy to Pages
    id-token: write # to verify the deployment originates from an authentic source

concurrency:
    group: 'pages'
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install TypeScript
              run: npm install -g typescript

            - name: Build (TypeScript)
              run: tsc -p tsconfig.json

            - name: Setup Pages
              uses: actions/configure-pages@v4

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  # Upload everything from the root directory
                  path: '.'

    deploy:
        needs: build
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
